# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eccac99b115c9456a84f8fb723a4fe97442b2e2fd6acc6e9ca42bc81206b95fe037b9704542e1f38298825c230236b4853e0cf862ea3e4d468b48db9caac4cc0

test:
  secret_key_base: c2908f8d9da1b72d0e588f4e55a443f770aa678fd0cde790ae5aaf04193eb99832af0c6983d609f67d982bf5af5f530436c3d79bcd9e34d9415fcba0836def29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
